// this code is autogenerated, do not modify!

import Swinject

extension Resolvable {

    func resolvePersonType() -> PersonType {
        return self.resolve(PersonType.self)!
    }
}

extension Container {

    func registerPersonType(registerClosure: (resolver: ResolverType) -> (PersonType)) -> ServiceEntry<PersonType> {
        return self.register(PersonType.self, factory: registerClosure)
    }
}
