# Uncomment this line to define a global platform for your project
platform :ios, "8.0"
# Uncomment this line if you're using Swift
use_frameworks!

target "CodeGenerationExample" do
  pod 'Swinject', '2.0.0-beta.2'
  #pod "Swinject-CodeGen", git: "https://github.com/Swinject/Swinject-CodeGen.git"
end
